### ISSUE TITLE
Question about the release date for the repository and dataset

### ISSUE THREAD

**Issue by TianYifan-Vincent** [ucla-mobility/V2X-Real#1]
Thank you for your great work on this project! I am very interested in the repository and dataset. Could you please let us know if you have an estimated release date for the code and data? It would be incredibly helpful for my research.

Looking forward to your response, and thank you for sharing this amazing work with the community!

**Comment by sethzhao506** [comment]
Please check https://mobility-lab.seas.ucla.edu/v2x-real/ for more updates.
