### ISSUE TITLE
Data Incompleteness in V2X-Real-Lidar-64 Training Set

### ISSUE THREAD

**Issue by rujiawang329** [ucla-mobility/V2X-Real#6]
# Data Incompleteness in V2X-Real-Lidar-64 Training Set

## Description
Found an incomplete data file in the V2X-Real-Lidar-64 dataset (OPV2V format). In training set 4, specifically in the directory `2023-04-07-14-47-37_17_1/1/`, there is only one file `000000.bin` present, while other necessary files (such as yaml files) are missing.

## Details
- **Dataset**: V2X-Real-Lidar-64 (OPV2V format)
- **Location**: Training Set 4
- **Specific Path**: `2023-04-07-14-47-37_17_1/1/`
- **Current State**: Only contains `000000.bin`
- **Expected State**: Should contain corresponding yaml files and complete sequence of bin files

## Dataset Source
The dataset can be accessed through: https://ucla.app.box.com/s/tre8f2n816n4dfqodp74cnqfz7on5qw2

**Comment by zhz03** [comment]
Thank you for bringing up this issue, we will fix it soon. Please refer to our latest released most completed dataset: V2X-Real-Lidar-Cameras. I think this one doesn't have such issue.

**Comment by rujiawang329** [comment]
> Thank you for bringing up this issue, we will fix it soon. Please refer to our latest released most completed dataset: V2X-Real-Lidar-Cameras. I think this one doesn't have such issue.

Ok, thanks.
